# Generated by Django 4.2 on 2025-04-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='noofseat',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
