# Generated by Django 4.2 on 2025-04-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ticket_noofseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='totalprice',
            field=models.FloatField(null=True),
        ),
    ]
