# Generated by Django 4.2 on 2025-04-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ticket_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
