# Generated by Django 4.2 on 2025-05-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ticket_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='totalprice',
            new_name='total_price',
        ),
    ]
